ALTER TABLE personas ADD COLUMN IF NOT EXISTS username TEXT NOT NULL DEFAULT '';
ALTER TABLE personas ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';
ALTER TABLE personas ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';
